[project]
name = "llms-know-difficulty"
version = "0.1.0"
description = "Package of experiments for llms know difficulty project"
requires-python = ">=3.12"
dependencies = [
    "accelerate==1.4.0",
    "bitsandbytes>=0.46.0",
    "datasets>=3.6.0",
    "deepspeed>=0.17.1",
    "dotenv>=0.9.9",
    "ipykernel>=6.29.5",
    "math-verify>=0.8.0",
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "pandas>=2.3.0",
    "peft==0.15.1",
    "regex>=2024.11.6",
    "scikit-learn>=1.7.0",
    "scipy>=1.15.3",
    "seaborn>=0.13.2",
    "sentencepiece>=0.2.0",
    "setuptools>=80.9.0",
    "tiktoken>=0.9.0",
    "torch>=2.7.1",
    "tqdm>=4.67.1",
    "transformers==4.49.0",
    "trl",
    "wandb>=0.20.1",
    "pytest",
    "pytest-cov",
    "black",
    "flake8",
    "mypy",
    "einops>=0.8.1",
    "jaxtyping>=0.3.4",
]

[tool.uv]
package = false
