name: dfr
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py310h25320af_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.21.3=h723845a_4
  - ld_impl_linux-64=2.40=h12ee557_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgomp=15.1.0=h767d61c_4
  - libkrb5=1.21.3=h520c7b4_4
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lmdb=0.9.31=hd590300_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.2=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py310h7c4b9e2_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.18=hd6af730_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pyzmq=27.0.2=py310h2a45ed9_1
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.4=hbc0de68_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_hd72426e_102
  - tornado=6.5.2=py310h7c4b9e2_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiohttp-cors==0.8.1
      - aiosignal==1.4.0
      - airportsdata==20250811
      - annotated-types==0.7.0
      - anthropic==0.64.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - av==15.0.0
      - blake3==1.0.5
      - cachetools==5.5.2
      - certifi==2025.8.3
      - cffi==1.17.1
      - cfgv==3.4.0
      - charset-normalizer==3.4.3
      - click==8.2.1
      - cloudpickle==3.1.1
      - codetiming==1.4.0
      - colorful==0.5.7
      - compressed-tensors==0.9.3
      - cuda-bindings==13.0.1
      - cuda-pathfinder==1.1.0
      - cuda-python==13.0.1
      - cupy-cuda12x==13.6.0
      - datasets==4.0.0
      - decord==0.6.0
      - deprecated==1.2.18
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - dnspython==2.7.0
      - einops==0.8.1
      - email-validator==2.2.0
      - fastapi==0.116.1
      - fastapi-cli==0.0.8
      - fastapi-cloud-cli==0.1.5
      - fastrlock==0.8.3
      - filelock==3.19.1
      - flash-attn==2.7.4.post1
      - flashinfer-python==0.2.2.post1+cu124torch2.6
      - frozendict==2.4.6
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - googleapis-common-protos==1.70.0
      - grpcio==1.74.0
      - h11==0.16.0
      - hf-transfer==0.1.9
      - hf-xet==1.1.8
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - hydra-core==1.3.2
      - identify==2.6.13
      - idna==3.10
      - importlib-metadata==8.0.0
      - iniconfig==2.1.0
      - interegular==0.3.3
      - jinja2==3.1.6
      - jiter==0.10.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - lark==1.2.2
      - latex2sympy2-extended==1.10.2
      - liger-kernel==0.6.2
      - litellm==1.75.9
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.12
      - markdown==3.8.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - math-verify==0.8.0
      - mathruler==0.1.0
      - mdurl==0.1.2
      - mistral-common==1.8.4
      - modelscope==1.29.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - msgspec==0.19.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - nanobind==2.8.0
      - networkx==3.4.2
      - ninja==1.13.0
      - nodeenv==1.9.1
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - openai==1.101.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-fixer==0.2.5
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - opentelemetry-api==1.36.0
      - opentelemetry-exporter-otlp==1.26.0
      - opentelemetry-exporter-otlp-proto-common==1.26.0
      - opentelemetry-exporter-otlp-proto-grpc==1.26.0
      - opentelemetry-exporter-otlp-proto-http==1.26.0
      - opentelemetry-exporter-prometheus==0.57b0
      - opentelemetry-proto==1.26.0
      - opentelemetry-sdk==1.36.0
      - opentelemetry-semantic-conventions==0.57b0
      - opentelemetry-semantic-conventions-ai==0.4.13
      - optree==0.17.0
      - orjson==3.11.2
      - outlines==0.1.11
      - outlines-core==0.1.26
      - pandas==2.3.2
      - parso==0.8.4
      - partial-json-parser==0.2.1.1.post6
      - peft==0.17.1
      - pillow==11.3.0
      - pluggy==1.6.0
      - pre-commit==4.3.0
      - prometheus-client==0.22.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==4.25.8
      - py-cpuinfo==9.0.0
      - py-spy==0.4.1
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==3.0.1
      - pycountry==24.6.1
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-extra-types==2.10.5
      - pyext==0.7
      - pylatexenc==2.10
      - pynvml==12.0.0
      - pytest==8.4.1
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - qwen-vl-utils==0.0.11
      - ray==2.48.0
      - referencing==0.36.2
      - regex==2025.7.34
      - requests==2.32.5
      - rich==14.1.0
      - rich-toolkit==0.15.0
      - rignore==0.6.4
      - rpds-py==0.27.0
      - rsa==4.9.1
      - ruff==0.12.10
      - safetensors==0.6.2
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.35.0
      - setproctitle==1.3.6
      - sgl-kernel==0.1.0
      - sglang==0.4.6.post1
      - shellingham==1.5.4
      - smart-open==7.3.0.post1
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - starlette==0.47.2
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensordict==0.6.2
      - tiktoken==0.11.0
      - tokenizers==0.21.4
      - tomli==2.2.1
      - torch==2.6.0
      - torch-memory-saver==0.0.8
      - torchao==0.12.0
      - torchaudio==2.6.0
      - torchdata==0.11.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.51.1
      - triton==3.2.0
      - typer==0.16.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - uvloop==0.21.0
      - verl==0.5.0.dev0
      - virtualenv==20.34.0
      - vllm==0.8.5.post1
      - wandb==0.21.1
      - watchfiles==1.1.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.3
      - xformers==0.0.29.post2
      - xgrammar==0.1.18
      - xxhash==3.5.0
      - yarl==1.20.1
prefix: /opt/anaconda/envs/dfr
